In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [11]:
data = pd.read_csv('data/Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [13]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [14]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [15]:
# concatenation with one hot encoded data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [16]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [17]:
# Split the data into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
# Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
## load the encoder and scaler for later one
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler,file)

### ANN Regression Problem Statement

In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From d:\Learning-In-Public\Deep_Learning\projects\01_Churn_Modelling\churnm_env\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [21]:
# Build our ANN Model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), # HL1 connected with input layer
    Dense(32,activation='relu'), # HL2
    Dense(1) # Output Layer
])

# compile the model
model.compile(optimizer='adam', loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From d:\Learning-In-Public\Deep_Learning\projects\01_Churn_Modelling\churnm_env\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From d:\Learning-In-Public\Deep_Learning\projects\01_Churn_Modelling\churnm_env\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [22]:
# Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [23]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [24]:
# Train the Model
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\Learning-In-Public\Deep_Learning\projects\01_Churn_Modelling\churnm_env\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\Learning-In-Public\Deep_Learning\projects\01_Churn_Modelling\churnm_env\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 4s 6ms/step - loss: 100376.6172 - mae: 100376.6172 - val_loss: 98512.6016 - val_mae: 98512.6016
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99609.5859 - mae: 99609.5859 - val_loss: 96954.6953 - val_mae: 96954.6953
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 96895.0000 - mae: 96895.0000 - val_loss: 92972.0078 - val_mae: 92972.0078
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 91582.0312 - mae: 91582.0312 - val_loss: 86374.1406 - val_mae: 86374.1406
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 83831.5234 - mae: 83831.5234 - val_loss: 77841.0859 - val_mae: 77841.0859
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 74706.1562 - mae: 74706.1562 - val_loss: 68897.7656 - val_mae: 68897.7656
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 65862.0859 - mae: 65862.0859 - val_loss: 61149.9492 - val_mae: 61149.9492
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 58838.8594 - mae: 58838.8594 - val_loss: 55754.6992 - val_mae: 55754.6992
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 54293.2891 - mae: 54293.2891 - val_loss: 52641.0586 - val_mae: 52641.0586
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 51884.6758 - mae: 51884.6758 - val_loss: 51362.5391 - val_mae: 51362.5391
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 50872.2383 - mae: 50872.2383 - val_loss: 51006.5000 - val_mae: 51006.5000
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50517.6680 - mae: 50517.6680 - val_loss: 50880.4023 - val_mae: 50880.4023
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50359.4922 - mae: 50359.4922 - val_loss: 50814.8516 - val_mae: 50814.8516
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50269.1602 - mae: 50269.1602 - val_loss: 50765.3203 - val_mae: 50765.3203
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 50203.6289 - mae: 50203.6289 - val_loss: 50726.0156 - val_mae: 50726.0156
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 50147.9531 - mae: 50147.9531 - val_loss: 50692.8359 - val_mae: 50692.8359
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50101.6719 - mae: 50101.6719 - val_loss: 50657.7891 - val_mae: 50657.7891
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50058.8398 - mae: 50058.8398 - val_loss: 50626.1953 - val_mae: 50626.1953
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 50017.3047 - mae: 50017.3047 - val_loss: 50593.5156 - val_mae: 50593.5156
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 49980.1133 - mae: 49980.1133 - val_loss: 50568.6016 - val_mae: 50568.6016
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49949.7344 - mae: 49949.7344 - val_loss: 50533.3125 - val_mae: 50533.3125
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 49919.4258 - mae: 49919.4258 - val_loss: 50515.9883 - val_mae: 50515.9883
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49893.8242 - mae: 49893.8242 - val_loss: 50489.9922 - val_mae: 50489.9922
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49866.7461 - mae: 49866.7461 - val_loss: 50469.2109 - val_mae: 50469.2109
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49841.8555 - mae: 49841.8555 - val_loss: 50447.0391 - val_mae: 50447.0391
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 49819.4492 - mae: 49819.4492 - val_loss: 50439.8867 - val_mae: 50439.8867
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49798.1211 - mae: 49798.1211 - val_loss: 50421.8516 - val_mae: 50421.8516
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49778.4336 - mae: 49778.4336 - val_loss: 50411.1953 - val_mae: 50411.1953
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49761.0000 - mae: 49761.0000 - val_loss: 50401.8477 - val_mae: 50401.8477
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49743.0508 - mae: 49743.0508 - val_loss: 50388.2266 - val_mae: 50388.2266
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49725.7031 - mae: 49725.7031 - val_loss: 50377.6367 - val_mae: 50377.6367
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49709.9531 - mae: 49709.9531 - val_loss: 50370.4141 - val_mae: 50370.4141
Epoch 33/100
250/250 [==============================] - 1s 4ms/step - loss: 49696.0234 - mae: 49696.0234 - val_loss: 50363.4414 - val_mae: 50363.4414
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49678.3164 - mae: 49678.3164 - val_loss: 50343.0625 - val_mae: 50343.0625
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49664.9102 - mae: 49664.9102 - val_loss: 50349.3203 - val_mae: 50349.3203
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 49652.0273 - mae: 49652.0273 - val_loss: 50337.2656 - val_mae: 50337.2656
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49635.8789 - mae: 49635.8789 - val_loss: 50323.4648 - val_mae: 50323.4648
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49623.7930 - mae: 49623.7930 - val_loss: 50313.0469 - val_mae: 50313.0469
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 49615.8164 - mae: 49615.8164 - val_loss: 50306.4648 - val_mae: 50306.4648
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 49599.9844 - mae: 49599.9844 - val_loss: 50310.5859 - val_mae: 50310.5859
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49591.9297 - mae: 49591.9297 - val_loss: 50303.4805 - val_mae: 50303.4805
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49578.9336 - mae: 49578.9336 - val_loss: 50300.9141 - val_mae: 50300.9141
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49569.1484 - mae: 49569.1484 - val_loss: 50296.9961 - val_mae: 50296.9961
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 49561.0859 - mae: 49561.0859 - val_loss: 50287.0352 - val_mae: 50287.0352
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49547.7031 - mae: 49547.7031 - val_loss: 50287.5664 - val_mae: 50287.5664
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 49538.7070 - mae: 49538.7070 - val_loss: 50290.5742 - val_mae: 50290.5742
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 49532.8164 - mae: 49532.8164 - val_loss: 50287.6016 - val_mae: 50287.6016
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49522.4766 - mae: 49522.4766 - val_loss: 50281.5547 - val_mae: 50281.5547
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49515.0859 - mae: 49515.0859 - val_loss: 50284.2930 - val_mae: 50284.2930
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49506.3711 - mae: 49506.3711 - val_loss: 50287.4336 - val_mae: 50287.4336
Epoch 51/100
250/250 [==============================] - 1s 4ms/step - loss: 49500.5938 - mae: 49500.5938 - val_loss: 50282.5625 - val_mae: 50282.5625
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49488.1094 - mae: 49488.1094 - val_loss: 50278.6953 - val_mae: 50278.6953
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 49484.9883 - mae: 49484.9883 - val_loss: 50272.5195 - val_mae: 50272.5195
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49476.9102 - mae: 49476.9102 - val_loss: 50277.4531 - val_mae: 50277.4531
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49473.9570 - mae: 49473.9570 - val_loss: 50275.7773 - val_mae: 50275.7773
Epoch 56/100
250/250 [==============================] - 1s 4ms/step - loss: 49467.2656 - mae: 49467.2656 - val_loss: 50282.4141 - val_mae: 50282.4141
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 49458.0078 - mae: 49458.0078 - val_loss: 50284.4688 - val_mae: 50284.4688
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 49455.2227 - mae: 49455.2227 - val_loss: 50277.1172 - val_mae: 50277.1172
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 49448.8203 - mae: 49448.8203 - val_loss: 50282.9844 - val_mae: 50282.9844
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 49442.0117 - mae: 49442.0117 - val_loss: 50272.8828 - val_mae: 50272.8828
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 49435.6406 - mae: 49435.6406 - val_loss: 50281.5312 - val_mae: 50281.5312
Epoch 62/100
250/250 [==============================] - 1s 4ms/step - loss: 49433.0039 - mae: 49433.0039 - val_loss: 50282.4844 - val_mae: 50282.4844
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 49429.7812 - mae: 49429.7812 - val_loss: 50275.7070 - val_mae: 50275.7070

In [25]:
# Load Tensorboard Extension
%load_ext tensorboard

In [27]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 18936), started 0:00:30 ago. (Use '!kill 18936' to kill it.)

In [28]:
# Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Test MAE: {test_mae}")

63/63 [==============================] - 0s 2ms/step - loss: 50272.5195 - mae: 50272.5195
Test MAE: 50272.51953125

In [29]:
model.save('regression_model.h5')

d:\Learning-In-Public\Deep_Learning\projects\01_Churn_Modelling\churnm_env\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(